resolver: lts-15.6

packages:
  - .
  # - ../web-rep

extra-deps:
  - box-0.3.0
  - interpolatedstring-perl6-1.0.2
  - javascript-bridge-0.2.0
  - lucid-svg-0.7.1
  - numhask-space-0.3.1
  - tdigest-0.2.1
  - text-format-0.3.2
  # - web-rep-0.3.2
  - git: https://github.com/tonyday567/web-rep
    commit: 0863a2974af30ece6cb46fb8a1198cb9b053c5e2
