resolver: nightly-2020-06-25

packages:
  - .

extra-deps:
  - git: https://github.com/tonyday567/numhask-space
    commit: 74de4262c333568c53c57c991c9f581d1ff6d474
  - git: https://github.com/tonyday567/web-rep
    commit: a13e55c3991353e552a67f8728e5fc228fff5d3e
  - git: https://github.com/tonyday567/box
    commit: d4a90748d3925b39df5aeeb88996d98cd9602ca9
  - javascript-bridge-0.2.0
  - lucid-svg-0.7.1
  - text-format-0.3.2

allow-newer: true
