resolver: lts-12.20

packages:
  - .
  - ../numhask/numhask
  - ../numhask/numhask-prelude
  - ../numhask/numhask-hedgehog
  - ../numhask/numhask-space
  # - ../numhask-range/numhask-range

extra-deps: []

