resolver: nightly-2019-03-15

packages:
  - .

extra-deps:
  - git: https://github.com/tonyday567/numhask.git
    commit: 717b02421d57b61890f21b9102c262628a98c968
    subdirs:
      - numhask
      - numhask-prelude
      - numhask-space


