resolver: nightly-2020-06-25

packages:
  - .

extra-deps:
  - git: https://github.com/tonyday567/numhask-space
    commit: 6525f5096525196fe367dabdfe596a7bd0c0aa6c
  - git: https://github.com/tonyday567/numhask
    commit: 37ee8dced120f60a511baa6bb6c7ac382b1e8827
    subdir: numhask-prelude
  - git: https://github.com/tonyday567/numhask
    commit: 37ee8dced120f60a511baa6bb6c7ac382b1e8827
    subdir: numhask
  - git: https://github.com/tonyday567/box
    commit: 6df3c4542ead135d31d0e1d7d06dcc2052915079
  - git: https://github.com/tonyday567/web-rep
    commit: 3bd6b82c33a80b4f7c785e042839be9d12fab3de
  - javascript-bridge-0.2.0

allow-newer: true
